// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoQ50-dSc9AR1giLgb1rjLfqr0me3z078',
    appId: '1:695574562874:android:f85bd5d5398bc0e72a8d03',
    messagingSenderId: '695574562874',
    projectId: 'project-manager-9ed58',
    storageBucket: 'project-manager-9ed58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBANDHOmutAE-VYPEWUxqccGfI_ZJkCiLo',
    appId: '1:695574562874:ios:7e22b162040efd332a8d03',
    messagingSenderId: '695574562874',
    projectId: 'project-manager-9ed58',
    storageBucket: 'project-manager-9ed58.firebasestorage.app',
    iosBundleId: 'co.enspyr.ourmealsmobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA30tVSjp3Pzaaf4dRexu9HtZYpcKbefXI',
    appId: '1:695574562874:web:69bc8faaf4809e472a8d03',
    messagingSenderId: '695574562874',
    projectId: 'project-manager-9ed58',
    authDomain: 'project-manager-9ed58.firebaseapp.com',
    storageBucket: 'project-manager-9ed58.firebasestorage.app',
  );

}